"""converting exchange_rate and estimated_gdp to allow null

Revision ID: a8f12dce70a4
Revises: 
Create Date: 2025-10-26 13:12:36.637616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a8f12dce70a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('country', 'exchange_rate',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('country', 'estimated_gdp',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_index(op.f('ix_country_estimated_gdp'), table_name='country')
    op.drop_index(op.f('ix_country_exchange_rate'), table_name='country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_country_exchange_rate'), 'country', ['exchange_rate'], unique=False)
    op.create_index(op.f('ix_country_estimated_gdp'), 'country', ['estimated_gdp'], unique=False)
    op.alter_column('country', 'estimated_gdp',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('country', 'exchange_rate',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
