"""correcting column name from flag_url to flag

Revision ID: cc1b79a8ac6b
Revises: a8f12dce70a4
Create Date: 2025-10-26 13:23:05.677633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc1b79a8ac6b'
down_revision: Union[str, Sequence[str], None] = 'a8f12dce70a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('flag', sa.String(length=255), nullable=True))
    op.drop_column('country', 'flag_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('flag_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('country', 'flag')
    # ### end Alembic commands ###
